### ISSUE TITLE
[BUG] Broken QQ faces

### ISSUE THREAD

**Issue by jyi2ya** [gongchen618/bug-carrot#2]
![issue](https://user-images.githubusercontent.com/86813521/167130032-7c67a3b4-f669-4b16-8942-2dd19a4d41d7.jpg)

**Comment by ligen131** [comment]
This may be related to the QQ version. Some old versions of QQ cannot show the face correctly. Please update your QQ to the lastest version.

**Comment by gongchen618** [comment]
sorry for that feature /剪刀

**Comment by gongchen618** [comment]
fix now!
